// DIFFERENTIAL_DIAGNOSIS capability — permanent regression suite.
//
// Exercises the full real pipeline (streamCopilotResponse → context build →
// mock AI → validateResponse) the same way capability-service.test.ts does
// for every other capability — not the validator in isolation — so this also
// proves the prompt/service/validator wiring for this capability stays intact.
//
// Every scenario here was manually verified once as a disposable scratch
// test during development (including the mixed-drift citation-bypass bug we
// found and its fix); this file makes each of them permanent.

import { describe, it, expect, vi, afterEach, beforeEach } from "vitest";
import { streamCopilotResponse } from "@/service/copilot";
import { setProvider, resetProvider } from "@/ai";
import * as ppmsClient from "@/lib/ppms-client";
import type { AIProvider, AiResult, AiStreamEvent } from "@/ai/provider";
import type { NdjsonFrame } from "@/service/copilot";
import {
  FIXTURE_PATIENT,
  FIXTURE_VISIT_CURRENT,
  FIXTURE_VISIT_PREVIOUS,
  FIXTURE_APPOINTMENTS,
  FIXTURE_TIMELINE,
  FIXTURE_TOKEN,
} from "./fixtures/patient";

// ── Mock AI provider ──────────────────────────────────────────────────────────

function makeMockProvider(responseText: string): AIProvider {
  return {
    id: "mock",
    model: "mock-model",
    isConfigured: () => true,
    async complete(): Promise<AiResult> {
      return {
        text: responseText,
        model: "mock-model",
        provider: "mock",
        usage: { inputTokens: 200, outputTokens: 100 },
        stopReason: "end_turn",
      };
    },
    async *stream(): AsyncIterable<AiStreamEvent> {
      const third = Math.ceil(responseText.length / 3);
      yield { type: "text", text: responseText.slice(0, third) };
      yield { type: "text", text: responseText.slice(third, third * 2) };
      yield { type: "text", text: responseText.slice(third * 2) };
      yield {
        type: "done",
        model: "mock-model",
        provider: "mock",
        usage: { inputTokens: 200, outputTokens: 100 },
        stopReason: "end_turn",
      };
    },
  };
}

async function collectFrames(
  body: Record<string, unknown>,
  authHeader: string,
): Promise<NdjsonFrame[]> {
  const frames: NdjsonFrame[] = [];
  for await (const frame of streamCopilotResponse(body, authHeader)) {
    frames.push(frame);
  }
  return frames;
}

function errorCodeOf(frames: NdjsonFrame[]): string | undefined {
  const errorFrame = frames.find((f) => f.type === "error");
  return errorFrame?.type === "error" ? errorFrame.code : undefined;
}

// ── Fixture response texts — one per scenario ─────────────────────────────────

const DISCLAIMER =
  "**IMPORTANT NOTICE — FOR DOCTOR REVIEW ONLY:** This list was generated by AI from the " +
  "documented patient record only. It is NOT a diagnosis and must NOT be used as one. It does " +
  "not include laboratory, imaging, or investigation result data. The doctor is solely " +
  "responsible for the final diagnostic decision and must not act on this output without " +
  "independent clinical assessment.";

// 1. Single cited item
const SINGLE_CITED_ITEM = `## Possible Considerations for Review
- **Anterior uveitis** — Moderate consideration (Source: V0 2024-06-15)
  **Supporting documented evidence:** Documented photophobia and eye pain at V0.

---
${DISCLAIMER}`;

// 2. Multi-item list, all cited
const MULTI_ITEM_ALL_CITED = `## Possible Considerations for Review
- **Anterior uveitis** — Moderate consideration (Source: V0 2024-06-15)
  **Supporting documented evidence:** Documented photophobia and eye pain at V0.
- **Episcleritis** — Low consideration (Finding 2, Source: V1 2023-12-10 → V0 2024-06-15)
  **Supporting documented evidence:** Documented redness without discharge.

---
${DISCLAIMER}`;

// 3. Item missing citation entirely
const ITEM_MISSING_CITATION = `## Possible Considerations for Review
- **Anterior uveitis** — Moderate consideration
  **Supporting documented evidence:** Documented photophobia.

---
${DISCLAIMER}`;

// 4. Non-citation parenthetical — "(likely)" is not a real evidence reference
const NON_CITATION_PARENTHETICAL = `## Possible Considerations for Review
- **Anterior uveitis** — Moderate consideration (likely)
  **Supporting documented evidence:** Documented photophobia.

---
${DISCLAIMER}`;

// 5. Disallowed confidence label implying certainty
const DISALLOWED_CONFIDENCE_LABEL = `## Possible Considerations for Review
- **Anterior uveitis** — High probability (Source: V0 2024-06-15)
  **Supporting documented evidence:** Documented photophobia.

---
${DISCLAIMER}`;

// 6. Exact insufficient-evidence sentence, zero items
const NO_EVIDENCE_SENTENCE = `## Possible Considerations for Review
The documented record does not contain sufficient findings to support any diagnostic considerations at this time.

---
${DISCLAIMER}`;

// 7. Missing the required heading entirely
const MISSING_HEADING =
  "Some free text response describing possible considerations informally, without using " +
  "the required structured heading or list format the prompt specifies at all.";

// 8. Prescriptive/treatment language mixed into an otherwise well-formed response
const PRESCRIPTIVE_LANGUAGE_MIXED_IN = `## Possible Considerations for Review
- **Anterior uveitis** — Moderate consideration (Source: V0 2024-06-15)
  **Supporting documented evidence:** Documented photophobia.
I recommend starting topical steroids immediately.

---
${DISCLAIMER}`;

// 9. Mixed well-formed + drifted item — the citation-bypass bug we found and fixed.
// The second item uses an en-dash (not the required hyphen/em-dash) and has no
// citation. Without the loose-candidate cross-check, the first item alone would
// make items.length > 0 and this uncited, drifted item would slip through unseen.
const MIXED_WELL_FORMED_AND_DRIFTED_ITEM = `## Possible Considerations for Review
- **Anterior uveitis** — Moderate consideration (Source: V0 2024-06-15)
  **Supporting documented evidence:** Documented photophobia.
- **Episcleritis** – Moderate consideration, given the documented redness pattern
  **Supporting documented evidence:** Documented redness.

---
${DISCLAIMER}`;

// 10. Abandoned/malformed fragment alongside the exact refusal sentence — the
// loose-candidate check must fire BEFORE the "noEvidence short-circuits" path,
// so a stray unclosed list item can't hide behind a valid refusal sentence.
const ABANDONED_FRAGMENT_WITH_REFUSAL_SENTENCE = `## Possible Considerations for Review
- **Possible glau
The documented record does not contain sufficient findings to support any diagnostic considerations at this time.

---
${DISCLAIMER}`;

// ── Test setup — mirrors capability-service.test.ts exactly ───────────────────

beforeEach(() => {
  process.env.PPMS_CORE_URL = "http://ppms-test.internal";
  vi.spyOn(ppmsClient, "getPatient").mockResolvedValue(FIXTURE_PATIENT);
  vi.spyOn(ppmsClient, "getVisit").mockResolvedValue(FIXTURE_VISIT_CURRENT);
  vi.spyOn(ppmsClient, "getVisits").mockResolvedValue([FIXTURE_VISIT_PREVIOUS]);
  vi.spyOn(ppmsClient, "getAppointments").mockResolvedValue(FIXTURE_APPOINTMENTS);
  vi.spyOn(ppmsClient, "getTimeline").mockResolvedValue(FIXTURE_TIMELINE);
});

afterEach(() => {
  vi.restoreAllMocks();
  resetProvider();
  delete process.env.PPMS_CORE_URL;
});

describe("DIFFERENTIAL_DIAGNOSIS capability", () => {
  it("1. single cited item passes, with correct done-frame meta", async () => {
    setProvider(makeMockProvider(SINGLE_CITED_ITEM));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);
    const done = frames.find((f) => f.type === "done");

    expect(done).toBeDefined();
    expect(frames.some((f) => f.type === "error")).toBe(false);
    if (done?.type === "done") {
      expect(done.meta.capability).toBe("DIFFERENTIAL_DIAGNOSIS");
      expect(done.meta.modelTier).toBe("reasoning");
      expect(done.meta.producesDraft).toBe(false);
    }
  });

  it("2. multi-item list, all items cited, passes", async () => {
    setProvider(makeMockProvider(MULTI_ITEM_ALL_CITED));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeDefined();
    expect(frames.some((f) => f.type === "error")).toBe(false);
  });

  it("3. item missing a citation is rejected as DIFFERENTIAL_UNCITED", async () => {
    setProvider(makeMockProvider(ITEM_MISSING_CITATION));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeUndefined();
    expect(errorCodeOf(frames)).toBe("DIFFERENTIAL_UNCITED");
  });

  it("4. a non-citation parenthetical like \"(likely)\" is rejected as uncited", async () => {
    setProvider(makeMockProvider(NON_CITATION_PARENTHETICAL));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeUndefined();
    expect(errorCodeOf(frames)).toBe("DIFFERENTIAL_UNCITED");
  });

  it("5. a disallowed confidence label (\"High probability\") is rejected as RESPONSE_UNSAFE", async () => {
    setProvider(makeMockProvider(DISALLOWED_CONFIDENCE_LABEL));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeUndefined();
    expect(errorCodeOf(frames)).toBe("RESPONSE_UNSAFE");
  });

  it("6. the exact insufficient-evidence sentence with zero items passes", async () => {
    setProvider(makeMockProvider(NO_EVIDENCE_SENTENCE));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeDefined();
    expect(frames.some((f) => f.type === "error")).toBe(false);
  });

  it("7. missing the required heading is rejected as DIFFERENTIAL_STRUCTURE_INVALID", async () => {
    setProvider(makeMockProvider(MISSING_HEADING));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeUndefined();
    expect(errorCodeOf(frames)).toBe("DIFFERENTIAL_STRUCTURE_INVALID");
  });

  it("8. prescriptive/treatment language mixed in is still rejected (universal check, unchanged)", async () => {
    setProvider(makeMockProvider(PRESCRIPTIVE_LANGUAGE_MIXED_IN));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeUndefined();
    expect(errorCodeOf(frames)).toBe("RESPONSE_UNSAFE");
  });

  it("9. a mixed well-formed + drifted item is rejected via the loose-candidate cross-check", async () => {
    setProvider(makeMockProvider(MIXED_WELL_FORMED_AND_DRIFTED_ITEM));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeUndefined();
    expect(errorCodeOf(frames)).toBe("DIFFERENTIAL_STRUCTURE_INVALID");
  });

  it("10. an abandoned fragment alongside the refusal sentence is rejected — noEvidence does not short-circuit it", async () => {
    setProvider(makeMockProvider(ABANDONED_FRAGMENT_WITH_REFUSAL_SENTENCE));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeUndefined();
    expect(errorCodeOf(frames)).toBe("DIFFERENTIAL_STRUCTURE_INVALID");
  });
});
