// DIFFERENTIAL_DIAGNOSIS capability — permanent regression suite.
//
// Exercises the full real pipeline (streamCopilotResponse → context build →
// mock AI → validateResponse) the same way capability-service.test.ts does
// for every other capability — not the validator in isolation — so this also
// proves the prompt/service/validator wiring for this capability stays intact.
//
// Output format: one block per consideration —
//   **[Diagnosis name]**
//   [Reason — one line]
//   Confidence: [Low / Moderate]
//   Source: [optional — omitted entirely when not tied to a specific finding]
// — blank line between blocks. Replaces an earlier single-line
// "- **Name** — confidence (citation)" format, which needed hardening twice
// against realistic model drift; this multi-line block format is parsed and
// validated field-by-field (see validateDifferentialDiagnosis in
// validation/response.ts) rather than via a single line-matching regex.

import { describe, it, expect, vi, afterEach, beforeEach } from "vitest";
import { streamCopilotResponse } from "@/service/copilot";
import { setProvider, resetProvider } from "@/ai";
import * as ppmsClient from "@/lib/ppms-client";
import type { AIProvider, AiResult, AiStreamEvent } from "@/ai/provider";
import type { NdjsonFrame } from "@/service/copilot";
import {
  FIXTURE_PATIENT,
  FIXTURE_VISIT_CURRENT,
  FIXTURE_VISIT_PREVIOUS,
  FIXTURE_APPOINTMENTS,
  FIXTURE_TIMELINE,
  FIXTURE_TOKEN,
} from "./fixtures/patient";

// ── Mock AI provider ──────────────────────────────────────────────────────────

function makeMockProvider(responseText: string): AIProvider {
  return {
    id: "mock",
    model: "mock-model",
    isConfigured: () => true,
    async complete(): Promise<AiResult> {
      return {
        text: responseText,
        model: "mock-model",
        provider: "mock",
        usage: { inputTokens: 200, outputTokens: 100 },
        stopReason: "end_turn",
      };
    },
    async *stream(): AsyncIterable<AiStreamEvent> {
      const third = Math.ceil(responseText.length / 3);
      yield { type: "text", text: responseText.slice(0, third) };
      yield { type: "text", text: responseText.slice(third, third * 2) };
      yield { type: "text", text: responseText.slice(third * 2) };
      yield {
        type: "done",
        model: "mock-model",
        provider: "mock",
        usage: { inputTokens: 200, outputTokens: 100 },
        stopReason: "end_turn",
      };
    },
  };
}

async function collectFrames(
  body: Record<string, unknown>,
  authHeader: string,
): Promise<NdjsonFrame[]> {
  const frames: NdjsonFrame[] = [];
  for await (const frame of streamCopilotResponse(body, authHeader)) {
    frames.push(frame);
  }
  return frames;
}

function errorCodeOf(frames: NdjsonFrame[]): string | undefined {
  const errorFrame = frames.find((f) => f.type === "error");
  return errorFrame?.type === "error" ? errorFrame.code : undefined;
}

// ── Fixture response texts — one per scenario ─────────────────────────────────

const DISCLAIMER =
  "**IMPORTANT NOTICE — FOR DOCTOR REVIEW ONLY:** This list was generated by AI from the " +
  "documented patient record only. It is NOT a diagnosis and must NOT be used as one. It does " +
  "not include laboratory, imaging, or investigation result data. The doctor is solely " +
  "responsible for the final diagnostic decision and must not act on this output without " +
  "independent clinical assessment.";

// 1. Well-formed block WITH a Source (citation) line.
const WELL_FORMED_WITH_CITATION = `## Possible Considerations for Review
**Anterior uveitis**
Documented photophobia and eye pain are consistent with anterior segment inflammation.
Confidence: Moderate
Source: V0 2024-06-15

---
${DISCLAIMER}`;

// 2. Well-formed block WITHOUT a Source line — general clinical reasoning,
// not tied to a specific documented finding. Citation is optional by design.
const WELL_FORMED_WITHOUT_CITATION = `## Possible Considerations for Review
**Early cataract changes**
Gradual blurring of vision is a general pattern consistent with early lens changes.
Confidence: Low

---
${DISCLAIMER}`;

// Multi-item list mixing a cited and an uncited block — both forms in one response.
const MULTI_ITEM_MIXED = `## Possible Considerations for Review
**Anterior uveitis**
Documented photophobia and eye pain are consistent with anterior segment inflammation.
Confidence: Moderate
Source: V0 2024-06-15

**Early cataract changes**
Gradual blurring of vision is a general pattern consistent with early lens changes.
Confidence: Low

---
${DISCLAIMER}`;

// 3. Missing reason line — Confidence line comes directly after the name.
const MISSING_REASON_LINE = `## Possible Considerations for Review
**Anterior uveitis**
Confidence: Moderate
Source: V0 2024-06-15

---
${DISCLAIMER}`;

// 4. Missing Confidence line — Source line comes directly after the reason.
const MISSING_CONFIDENCE_LINE = `## Possible Considerations for Review
**Anterior uveitis**
Documented photophobia and eye pain reported.
Source: V0 2024-06-15

---
${DISCLAIMER}`;

// 5. Confidence line present but with a value outside "Low" / "Moderate".
const INVALID_CONFIDENCE_VALUE = `## Possible Considerations for Review
**Anterior uveitis**
Documented photophobia and eye pain reported.
Confidence: Medium

---
${DISCLAIMER}`;

// 6. Certainty language — hard-rejected regardless of block structure.
const CERTAINTY_LANGUAGE = `## Possible Considerations for Review
**Anterior uveitis**
This is a confirmed diagnosis based on the documented findings.
Confidence: Moderate
Source: V0 2024-06-15

---
${DISCLAIMER}`;

// 7. Prescriptive/treatment language mixed into an otherwise well-formed response.
const PRESCRIPTIVE_LANGUAGE_MIXED_IN = `## Possible Considerations for Review
**Anterior uveitis**
Documented photophobia and eye pain reported.
Confidence: Moderate
Source: V0 2024-06-15

I recommend starting topical steroids immediately.

---
${DISCLAIMER}`;

// 8. Malformed/drifted block — two considerations run together without a
// blank line between them, so they parse as a single 6-line block instead
// of two valid 4-line blocks. Rejected by the block length bound.
const MALFORMED_DRIFTED_BLOCK = `## Possible Considerations for Review
**Anterior uveitis**
Documented photophobia and eye pain reported.
Confidence: Moderate
**Episcleritis**
Documented redness without discharge.
Confidence: Low

---
${DISCLAIMER}`;

// 9. Missing the required heading entirely.
const MISSING_HEADING =
  "Some free text response describing possible considerations informally, without using " +
  "the required structured heading or block format the prompt specifies at all.";

// 10. Exact insufficient-evidence sentence, zero blocks.
const NO_EVIDENCE_SENTENCE = `## Possible Considerations for Review
The documented record does not contain sufficient findings to support any diagnostic considerations at this time.

---
${DISCLAIMER}`;

// 12. A well-intentioned reason that wraps across two lines with a hard
// newline (no blank line before Confidence) — not a separate field, just a
// long sentence that broke mid-clause. Must still pass: the reason is
// reconstructed from every line before the Confidence line, however many.
const WRAPPED_REASON_NO_SOURCE = `## Possible Considerations for Review
**Anterior uveitis**
Documented photophobia and eye pain are consistent with
anterior segment inflammation, warranting consideration.
Confidence: Moderate

---
${DISCLAIMER}`;

// 11. An abandoned/malformed fragment alongside the exact refusal sentence —
// the fragment must not be able to hide behind a valid refusal elsewhere in
// the same section. Fail closed rather than letting noEvidence short-circuit.
const ABANDONED_FRAGMENT_WITH_REFUSAL_SENTENCE = `## Possible Considerations for Review
**Possible glau

The documented record does not contain sufficient findings to support any diagnostic considerations at this time.

---
${DISCLAIMER}`;

// ── Test setup — mirrors capability-service.test.ts exactly ───────────────────

beforeEach(() => {
  process.env.PPMS_CORE_URL = "http://ppms-test.internal";
  vi.spyOn(ppmsClient, "getPatient").mockResolvedValue(FIXTURE_PATIENT);
  vi.spyOn(ppmsClient, "getVisit").mockResolvedValue(FIXTURE_VISIT_CURRENT);
  vi.spyOn(ppmsClient, "getVisits").mockResolvedValue([FIXTURE_VISIT_PREVIOUS]);
  vi.spyOn(ppmsClient, "getAppointments").mockResolvedValue(FIXTURE_APPOINTMENTS);
  vi.spyOn(ppmsClient, "getTimeline").mockResolvedValue(FIXTURE_TIMELINE);
});

afterEach(() => {
  vi.restoreAllMocks();
  resetProvider();
  delete process.env.PPMS_CORE_URL;
});

describe("DIFFERENTIAL_DIAGNOSIS capability", () => {
  it("1. well-formed block WITH a citation (Source line) passes, with correct done-frame meta", async () => {
    setProvider(makeMockProvider(WELL_FORMED_WITH_CITATION));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);
    const done = frames.find((f) => f.type === "done");

    expect(done).toBeDefined();
    expect(frames.some((f) => f.type === "error")).toBe(false);
    if (done?.type === "done") {
      expect(done.meta.capability).toBe("DIFFERENTIAL_DIAGNOSIS");
      expect(done.meta.modelTier).toBe("reasoning");
      expect(done.meta.producesDraft).toBe(false);
    }
  });

  it("2. well-formed block WITHOUT a citation (no Source line) also passes — citation is optional", async () => {
    setProvider(makeMockProvider(WELL_FORMED_WITHOUT_CITATION));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeDefined();
    expect(frames.some((f) => f.type === "error")).toBe(false);
  });

  it("multi-item list mixing a cited and an uncited block passes", async () => {
    setProvider(makeMockProvider(MULTI_ITEM_MIXED));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeDefined();
    expect(frames.some((f) => f.type === "error")).toBe(false);
  });

  it("3. a block missing its reason line is rejected as DIFFERENTIAL_STRUCTURE_INVALID", async () => {
    setProvider(makeMockProvider(MISSING_REASON_LINE));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeUndefined();
    expect(errorCodeOf(frames)).toBe("DIFFERENTIAL_STRUCTURE_INVALID");
  });

  it("4. a block missing its Confidence line is rejected as DIFFERENTIAL_STRUCTURE_INVALID", async () => {
    setProvider(makeMockProvider(MISSING_CONFIDENCE_LINE));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeUndefined();
    expect(errorCodeOf(frames)).toBe("DIFFERENTIAL_STRUCTURE_INVALID");
  });

  it("5. a Confidence value outside Low/Moderate is rejected as DIFFERENTIAL_STRUCTURE_INVALID", async () => {
    setProvider(makeMockProvider(INVALID_CONFIDENCE_VALUE));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeUndefined();
    expect(errorCodeOf(frames)).toBe("DIFFERENTIAL_STRUCTURE_INVALID");
  });

  it("6. certainty language is rejected as RESPONSE_UNSAFE regardless of block structure", async () => {
    setProvider(makeMockProvider(CERTAINTY_LANGUAGE));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeUndefined();
    expect(errorCodeOf(frames)).toBe("RESPONSE_UNSAFE");
  });

  it("7. prescriptive/treatment language mixed in is rejected as RESPONSE_UNSAFE (universal check, unchanged)", async () => {
    setProvider(makeMockProvider(PRESCRIPTIVE_LANGUAGE_MIXED_IN));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeUndefined();
    expect(errorCodeOf(frames)).toBe("RESPONSE_UNSAFE");
  });

  it("8. a malformed/drifted block (two considerations run together) is rejected as DIFFERENTIAL_STRUCTURE_INVALID", async () => {
    setProvider(makeMockProvider(MALFORMED_DRIFTED_BLOCK));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeUndefined();
    expect(errorCodeOf(frames)).toBe("DIFFERENTIAL_STRUCTURE_INVALID");
  });

  it("9. missing the required heading is rejected as DIFFERENTIAL_STRUCTURE_INVALID", async () => {
    setProvider(makeMockProvider(MISSING_HEADING));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeUndefined();
    expect(errorCodeOf(frames)).toBe("DIFFERENTIAL_STRUCTURE_INVALID");
  });

  it("10. the exact insufficient-evidence sentence with zero blocks passes", async () => {
    setProvider(makeMockProvider(NO_EVIDENCE_SENTENCE));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeDefined();
    expect(frames.some((f) => f.type === "error")).toBe(false);
  });

  it("11. an abandoned fragment alongside the refusal sentence is rejected — the valid sentence does not mask it", async () => {
    setProvider(makeMockProvider(ABANDONED_FRAGMENT_WITH_REFUSAL_SENTENCE));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeUndefined();
    expect(errorCodeOf(frames)).toBe("DIFFERENTIAL_STRUCTURE_INVALID");
  });

  it("12. a reason that wraps across two lines with a hard newline (no blank line before Confidence) now passes", async () => {
    setProvider(makeMockProvider(WRAPPED_REASON_NO_SOURCE));

    const frames = await collectFrames({ capability: "DIFFERENTIAL_DIAGNOSIS" }, `Bearer ${FIXTURE_TOKEN}`);

    expect(frames.find((f) => f.type === "done")).toBeDefined();
    expect(frames.some((f) => f.type === "error")).toBe(false);
  });
});
